name: packaging

on: workflow_call

jobs:
  prepare-artifacts:
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['21.3', '22.2']
        elixir: ['1.8.2', '1.9.4']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3

  build-docker:
    if: (github.ref_name == 'master' && !startsWith(github.ref, 'refs/tags'))
    needs: prepare-artifacts
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['21.3', '22.2']
        elixir: ['1.8.2', '1.9.4']
    environment: production
    steps:
      - name: build-n-publish docker image
        run: |
          echo "Imagine a magic code building images here"

  build-docker-staging:
    if: (!startsWith(github.ref, 'refs/tags'))
    needs: prepare-artifacts
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['21.3', '22.2']
        elixir: ['1.8.2', '1.9.4']
    environment: staging
    steps:
      - name: build-n-publish docker image
        run: |
          echo "Imagine a magic code building images here"

  publish-chart:
    if: (github.ref_name == 'master' && !startsWith(github.ref, 'refs/tags'))
    needs: build-docker
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['21.3', '22.2']
        elixir: ['1.8.2', '1.9.4']
    environment: production
    env:
      VERSION: 0.0.${{ github.run_id }}
    steps:
      - name: Publish Helm chart gha-sandbox ${{ env.VERSION }}
        run: |
          echo "Imagine a magic code building helm charts here"

  publish-chart-staging:
    if: (!startsWith(github.ref, 'refs/tags'))
    needs: build-docker-staging
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['21.3', '22.2']
        elixir: ['1.8.2', '1.9.4']
    environment: staging
    env:
      VERSION: 0.0.${{ github.run_id }}
    steps:
      - name: Publish Helm chart gha-sandbox ${{ env.VERSION }}
        run: |
          echo "Imagine a magic code building helm charts here"

